name: 'Close Stale Discussions'
description: 'Close discussions with no recent activity'
author: 'Steffen Wirenfeldt Karlsson'

inputs:
  repo-token:
    description:
      'Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN
      }}`.'
    required: false
    default: ${{ github.token }}
  message:
    description:
      'The message to post on the discussion when closing it, if any. Defaults
      to no message.'
    required: false
  days-before-close:
    description: 'The number of days to wait to close a stale discussion.'
    required: false
    default: '7'
  close-reason:
    description: 'The reason to use when closing a discussion.'
    required: false
    default: 'outdated'
  debug-only:
    description:
      'Run the processor in debug mode without actually performing any
      operations on live discussions.'
    required: false
    default: 'false'

outputs:
  closed-discussions:
    description: 'List of all closed discussions.'

runs:
  using: node20
  main: dist/index.js
