name: 'StaleSweeper'
description:
  'Automatically closes stale discussions to declutter your GitHub repository.'
author: 'Steffen Wirenfeldt Karlsson'
branding:
  icon: 'message-circle'
  color: 'green'

inputs:
  repo-token:
    description:
      'Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN
      }}`.'
    required: false
    default: ${{ github.token }}
  message:
    description:
      'The message to post on the discussion when closing it. Defaults
      to no message.'
    required: false
  days-before-close:
    description: 'The number of days to wait before closing a stale discussion.'
    required: true
  close-unanswered:
    description:
      'If set to `true`, stale discussions that have not been marked as answered
      will also be closed.'
    required: false
    default: 'false'
  category:
    description:
      'The category of discussions to close. Defaults to all discussion types'
    required: false
  close-reason:
    description:
      'The reason to use when closing a discussion. Options include 
      `DUPLICATE`, `OUTDATED`, and `RESOLVED`.'
    required: false
    default: 'outdated'
  dry-run:
    description:
      'If set to `true`, the processor will run in debug mode without performing
       any operations on live discussions.'
    required: false
    default: 'false'

outputs:
  closed-discussions:
    description: 'Provides a list of all discussions that were closed.'

runs:
  using: node20
  main: dist/index.js
