name: Local Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Stalesweeper
        id: stalesweeper
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: 'This discussion has been closed due to inactivity.'
          days-before-close: '1'
          close-unanswered: 'false'
          close-reason: 'OUTDATED'
          dry-run: 'false'

      - name: Print Output
        id: output
        run: echo "${{ steps.stalesweeper.outputs.closed-discussions }}"
